name: Build PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Typst.
      run: brew install typst
      
    - name: Build PDFs.
      run: |
        typst compile resume-consulting.typ
        typst compile resume-engineering.typ
      
    - name: Create release.
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        files: |
          resume-consulting.pdf
          resume-engineering.pdf
        automatic_release_tag: "latest"
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
